package com.chronotrace.sdk

import org.gradle.testkit.runner.GradleRunner
import org.gradle.api.publish.Publication
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * Validates Maven publish configuration for the sdk-kmp KMP module.
 * Fails until the maven-publish plugin is correctly configured with
 * groupId, artifactId, and version for JVM/JS/Wasm targets.
 */
class MavenPublishConfigTest {

    @TempDir
    lateinit var projectDir: File

    private lateinit var settingsFile: File
    private lateinit var buildFile: File

    @BeforeEach
    fun setup() {
        settingsFile = File(projectDir, "settings.gradle.kts")
        buildFile = File(projectDir, "build.gradle.kts")

        // Minimal settings that include the sdk-kmp module
        settingsFile.writeText("""
            pluginManagement {
                repositories {
                    gradlePluginPortal()
                    mavenCentral()
                }
            }
            rootProject.name = "ChronoTrace"
            include(":sdk-kmp")
        """.trimIndent())

        // We just symlink to the real sdk-kmp so we test the real config
        val sdkKmpDir = File(projectDir, "sdk-kmp")
        sdkKmpDir.mkdirs()
        val realBuild = File("/home/cage/Desktop/Workspaces/ChronoTrace/sdk-kmp/build.gradle.kts")
        File(sdkKmpDir, "build.gradle.kts").writeText(realBuild.readText())
    }

    @Test
    fun `publishToMavenLocal --dry-run configures jvm publication with correct coordinates`() {
        // Use Gradle runner to inspect the publication model
        val runner = GradleRunner.create()
            .withProjectDir(projectDir)
            .withArguments(":sdk-kmp:publishToMavenLocal", "--dry-run")
            .withPluginClasspath()

        // This will fail because maven-publish plugin is not applied yet
        // After we add the plugin, it should pass
        val result = runner.build()
        assertTrue(result.output.contains("publishToMavenLocal") || result.output.contains("publish"))
    }

    @Test
    fun `pom file generated by publish task has correct groupId artifactId version`() {
        // Run the actual publish to a temp local repo (not MavenCentral)
        val runner = GradleRunner.create()
            .withProjectDir(File("/home/cage/Desktop/Workspaces/ChronoTrace"))
            .withArguments(
                ":sdk-kmp:publishJvmPublicationToMavenLocal",
                "--dry-run",
                "--info"
            )

        val result = runner.build()
        // If dry-run works, publication is configured correctly
        assertTrue(
            result.output.contains("jvm") || result.output.contains("MavenLocal"),
            "Expected publish task to reference JVM publication, got: ${result.output.take(500)}"
        )
    }
}