package org.chronotrace.contract

import java.io.File
import kotlinx.serialization.KSerializer
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.SerialKind
import kotlin.system.exitProcess

private data class TsDefinition(
    val name: String,
    val render: (TypeScriptContractGenerator) -> String,
)

class TypeScriptContractGenerator {
    private val scalarOverrides = mapOf(
        "kotlin.String" to "string",
        "kotlin.Int" to "number",
        "kotlin.Long" to "number",
        "kotlin.Boolean" to "boolean",
        "kotlin.Double" to "number",
        "kotlin.Float" to "number",
    )

    private val definitions = listOf(
        enumDefinition("LogLevel", LogLevel.serializer()),
        enumDefinition("CaptureReason", CaptureReason.serializer()),
        enumDefinition("SpanStatus", SpanStatus.serializer()),
        enumDefinition("PurgeJobStatus", PurgeJobStatus.serializer()),
        enumDefinition("ExpressionOperator", ExpressionOperator.serializer()),
        enumDefinition("RuleDeliveryStatus", RuleDeliveryStatus.serializer()),
        interfaceDefinition("ChronoInitConfig", ChronoInitConfig.serializer()),
        interfaceDefinition("ClientMetadata", ClientMetadata.serializer()),
        interfaceDefinition("CallStackItem", CallStackItem.serializer()),
        interfaceDefinition("SerializationMetadata", SerializationMetadata.serializer()),
        interfaceDefinition("LogRecord", LogRecord.serializer()),
        interfaceDefinition("SpanRecord", SpanRecord.serializer()),
        interfaceDefinition("FrameSnapshot", FrameSnapshot.serializer()),
        interfaceDefinition("RemoteRule", RemoteRule.serializer()),
        interfaceDefinition("RemoteRuleFeedback", RemoteRuleFeedback.serializer()),
        interfaceDefinition("RuleDeliveryConfirmation", RuleDeliveryConfirmation.serializer()),
        interfaceDefinition("PurgeSelector", PurgeSelector.serializer()),
        interfaceDefinition("PurgeJob", PurgeJob.serializer()),
        interfaceDefinition("IngestBatch", IngestBatch.serializer()),
        interfaceDefinition("IngestResponse", IngestResponse.serializer()),
        interfaceDefinition("IngestRejection", IngestRejection.serializer()),
        interfaceDefinition("SearchLogsRequest", SearchLogsRequest.serializer()),
        interfaceDefinition("SearchLogsResponse", SearchLogsResponse.serializer()),
        interfaceDefinition("TraceView", TraceView.serializer()),
        interfaceDefinition("SystemHealth", SystemHealth.serializer()),
        interfaceDefinition("ToolDescriptor", ToolDescriptor.serializer()),
        interfaceDefinition("ToolCallRequest", ToolCallRequest.serializer()),
        interfaceDefinition("ToolCallResponse", ToolCallResponse.serializer()),
    )

    fun render(): String {
        return buildString {
            appendLine("// GENERATED FROM chronotrace-contract")
            appendLine("// Generated by :chronotrace-contract:generateTypeScriptContracts")
            appendLine("// Do not edit by hand.")
            appendLine()
            definitions.forEachIndexed { index, definition ->
                appendLine(definition.render(this@TypeScriptContractGenerator))
                if (index != definitions.lastIndex) {
                    appendLine()
                }
            }
        }
    }

    private fun enumDefinition(name: String, serializer: KSerializer<*>): TsDefinition {
        return TsDefinition(name) {
            val variants = (0 until serializer.descriptor.elementsCount)
                .joinToString(" | ") { "\"${serializer.descriptor.getElementName(it)}\"" }
            "export type $name = $variants;"
        }
    }

    private fun interfaceDefinition(name: String, serializer: KSerializer<*>): TsDefinition {
        return TsDefinition(name) {
            val descriptor = serializer.descriptor
            buildString {
                appendLine("export interface $name {")
                repeat(descriptor.elementsCount) { index ->
                    val elementName = descriptor.getElementName(index)
                    val elementDescriptor = descriptor.getElementDescriptor(index)
                    val optionalMark = if (descriptor.isElementOptional(index) || elementDescriptor.isNullable) "?" else ""
                    appendLine("  $elementName$optionalMark: ${toTsType(elementDescriptor)};")
                }
                append("}")
            }
        }
    }

    private fun toTsType(descriptor: SerialDescriptor): String {
        val serialName = descriptor.serialName.removeSuffix("?")
        val baseType = scalarOverrides[serialName] ?: when (descriptor.kind) {
            StructureKinds.LIST -> "${toTsType(descriptor.getElementDescriptor(0))}[]"
            StructureKinds.MAP -> "Record<string, ${toTsType(descriptor.getElementDescriptor(1))}>"
            is PrimitiveKind -> when (descriptor.kind) {
                PrimitiveKind.STRING, PrimitiveKind.CHAR -> "string"
                PrimitiveKind.BOOLEAN -> "boolean"
                else -> "number"
            }

            SerialKind.ENUM -> {
                (0 until descriptor.elementsCount)
                    .joinToString(" | ") { "\"${descriptor.getElementName(it)}\"" }
            }

            StructureKinds.CLASS, StructureKinds.OBJECT -> serialName.substringAfterLast('.')
            else -> throw IllegalStateException("Unsupported SerialKind: ${descriptor.kind} for $serialName")
        }
        return if (descriptor.isNullable) "$baseType | null" else baseType
    }
}

private object StructureKinds {
    val LIST = kotlinx.serialization.descriptors.StructureKind.LIST
    val MAP = kotlinx.serialization.descriptors.StructureKind.MAP
    val CLASS = kotlinx.serialization.descriptors.StructureKind.CLASS
    val OBJECT = kotlinx.serialization.descriptors.StructureKind.OBJECT
}

fun main(args: Array<String>) {
    val checkMode = args.firstOrNull() == "--check"
    val outputPath = if (checkMode) args.getOrNull(1) else args.firstOrNull()
    require(outputPath != null) { "Output path is required" }

    val generator = TypeScriptContractGenerator()
    val rendered = generator.render()
    val outputFile = File(outputPath)

    if (checkMode) {
        val current = outputFile.takeIf(File::exists)?.readText()
        if (current != rendered) {
            System.err.println("TypeScript contract output is stale: ${outputFile.path}")
            exitProcess(1)
        }
        return
    }

    outputFile.parentFile.mkdirs()
    outputFile.writeText(rendered)
}
